### ISSUE TITLE
mergeArrays

### ISSUE THREAD

**Issue by groall** [drklauss/test_cURL#2]
function mergeArrays(array $arrayIndexes, array $arrayQuotes)
{
$final = array();
foreach ($arrayIndexes as $key => $index)
{
$final[$key]['index'] = $index;
$final[$key]['quote'] = $arrayQuotes[$key];
}
echo '<pre>';
print_r($final);
echo '</pre>';
}

**Comment by drklauss** [comment]
Да,жаль что я сам на радостях не заметил что они одинаковые. Ну,ниче. Логика ясна,теперь работа с БД предстоит
